### ISSUE TITLE
item with name 'solid-resin-1' does not exist

### ISSUE THREAD

**Issue by MysticTiger** [IanDuncanT/Aerogels#4]
I get this error on load

Not entirely sure if this is a problem with Aerogels or Angel's refining/petrochem
I have the latest versions of all mods installed including Angel's Refining, Angel's Petrochem, Angel's Bio-Processing, Angel's Smelting, and Bob's Revamp

I deleted and redownloaded Aerogels and now it still has the error but also says:
 "Source: resourcinol (recipe)."

**Comment by IanDuncanT** [comment]
I have updated on github will check the mod portal tonight. Reference issue #1
